# Generated by Django 2.2.4 on 2019-09-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=40, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('level_name', models.CharField(blank=True, max_length=40, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('req_id', models.CharField(blank=True, max_length=15, null=True)),
                ('request_payload', models.TextField(blank=True, null=True)),
                ('response_payload', models.TextField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=50, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=10, null=True)),
                ('order_place_date', models.DateTimeField(blank=True, null=True)),
                ('order_status', models.CharField(blank=True, max_length=20, null=True)),
                ('order_type', models.CharField(blank=True, max_length=10, null=True)),
                ('order_id', models.CharField(blank=True, max_length=40, null=True)),
                ('order_place_response', models.TextField(blank=True, null=True)),
                ('order_execution_response', models.TextField(blank=True, null=True)),
                ('order_execution_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
